# Generated by Django 5.1.3 on 2024-11-28 16:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailing_finish_send_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='finish_send_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время окончания отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='first_send_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время первой отправки'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='attempted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки отправки'),
        ),
    ]
