# Generated by Django 5.1.1 on 2024-11-23 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=50, verbose_name='Наименование категории')),
                ('description', models.TextField(help_text='Введите описание категории', max_length=1000, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категорию продукта',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название продукта', max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(help_text='Введите описание продукта', max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(help_text='Загрузите изображение продукта', upload_to='products/', verbose_name='Изображение продукта')),
                ('purchase_price', models.IntegerField(blank=True, help_text='Введите цену', null=True, verbose_name='Цена за покупку')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('published', models.BooleanField(default=False, help_text='Статус публикации продукта', verbose_name='Публикация')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product', to='catalog.category', verbose_name='Категория')),
                ('owner', models.ForeignKey(blank=True, help_text='Укажите владельца', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='номер версии')),
                ('name', models.CharField(default='Default Version Name', max_length=200, verbose_name='наименование версии')),
                ('version_flag', models.BooleanField(default=False, verbose_name='признак версии')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
                'ordering': ['product', 'version_number', 'name', 'version_flag'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('version_flag', True)), fields=('product', 'version_flag'), name='unique_active_version')],
            },
        ),
    ]
