# Generated by Django 5.1.1 on 2024-11-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'category'], 'permissions': [('can_publish_product', 'Может публиковать продукт'), ('can_edit_any_product', 'Может редактировать любой продукт')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
