# Generated by Django 5.1.1 on 2024-11-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='description',
            field=models.TextField(default='Нет описания'),
        ),
    ]
